### ISSUE TITLE
Error message when opening a file: Compiler not supported

### ISSUE THREAD

**Issue by jan0sch** [habamax/vim-asciidoctor#1]
Thanks for the plugin. Finally a decent asciidoc plugin for vim. :-)

If I open a asciidoc file I get the following error message:

```
Fehler beim Ausführen von "~/.config/nvim/bundle/vim-asciidoctor/ftplugin/asciidoctor.vim":
Zeile   10: E666: Compiler nicht unterstützt: Asciidoctor2HTML
```

The line causing the error message is here: https://github.com/habamax/vim-asciidoctor/blob/master/ftplugin/asciidoctor.vim#L10

### System environment

FreeBSD 12.0-p2
NeoVim 0.3.4
Asciidoctor 1.5.8

**Comment by habamax** [comment]
Hi, thx for the report.

Fixed it
