### ISSUE TITLE
 feature request: bibliography completion

### ISSUE THREAD

**Issue by Konfekt** [habamax/vim-asciidoctor#10]
Could an omni-completion function similar to that of `vim-pandoc` at

https://github.com/vim-pandoc/vim-pandoc/blob/660f556d1fdcede2900b12a09e1452fc5414ee82/autoload/pandoc/completion.vim#L40

be implemented in `vim-asciidoctor`?

**Comment by Konfekt** [comment]
By the way, perhaps https://github.com/Konfekt/FastFold/ might speed up editing asciidoc files by disabling the continuous recomputation of folds.

**Comment by habamax** [comment]
To be frank, I am not very good at vim omni-completion and at the same time have never used bibliographies.

**Comment by habamax** [comment]
Hi Konfekt,

I have added initial support for bibtex citation completion with `<C-X><C-U>`:

![image](https://user-images.githubusercontent.com/234774/67770793-2113cf80-fa68-11e9-9acf-be9ae9ef9d0f.png)

Could you try if it works for you?

**Comment by habamax** [comment]
Probably type of a citation (book, article, mastersthesis, etc) could be also added to completion menu -- have to dig it out.

**Comment by habamax** [comment]
Type is added :)

**Comment by Konfekt** [comment]
Yes, works impeccably with a bib file of the same name (minus the extension) as the asciidoctor file.

**Comment by habamax** [comment]
It should work with all bib files in the same directory with adoc file you are editing. It combines all of them no matter what the name is. Or at least it should do so ;)

**Comment by Konfekt** [comment]
Okay, that's what was meant by next to it. I though that asciidoctor has a setting similar to pandoc's
```
bibliography:         test.bib
```
in the files `Yaml` header.

**Comment by habamax** [comment]
It has, but i didnt figure out how it should work. 

So for completion I just use all bib files.

Check asciidoctor-bibtex extension
