### ISSUE TITLE
Add mapping to "open link under cursor"

### ISSUE THREAD

**Issue by sotte** [habamax/vim-asciidoctor#100]
First of all: great plugin @habamax!

Second: maybe a bit out of scope, but I'll give it a try anyway. Feel free to close this.

I have lot's of links to local adoc files: `link:my_note.adoc[Title of My Note]`. It would be great if this plugin supported a mapping similar to `ge` from `plasicoy/vim-markdown`, basically "open link under the cursor".

https://github.com/plasticboy/vim-markdown/blob/master/doc/vim-markdown.txt#L518
https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L666

What do you think?

**Comment by habamax** [comment]
* `gx` opens link in an external app
* `gf` opens include links in vim, probably I should also add regular links to it.

**Comment by habamax** [comment]
Pls check `gf` and `link:my_note.adoc[Title of My Note]`

**Comment by sotte** [comment]
Thanks for the quick response.

`gx` is super useful and I use it all the time, same for `gf`.

The problem with `gf` and links is that you have to be on the actual path to the file of a like like `link:my_note.adoc[This is a note]`. It does not work if the cursor is on `n` of note.
If you have `conceal>0` you don't even really see where the cursor is.

**Comment by habamax** [comment]
> The problem with `gf` and links is that you have to be on the actual path to the file of a like like `link:my_note.adoc[This is a note]`. It does not work if the cursor is on `n` of note.
> If you have `conceal>0` you don't even really see where the cursor is.

Well I use "default" way to handle `gf`, using `includeexpr` which is based on a `WORD` under a cursor (afaik). It means spaces are the issue. In your link you would be able to open a file if your cursor is on any char before the first space.

Let me think about solution.

**Comment by habamax** [comment]
`gx` works for a `link:https://ya.ru[This is a note]`, I think it is possible to use the same for `gf` but not sure if shadowing it would be a nice idea.

**Comment by sotte** [comment]
> Well I use "default" way to handle gf, using includeexpr which is based on a WORD under a cursor (afaik). It means spaces are the issue.

Agree.

> gx works for a link:https://ya.ru[This is a note]

Yes, same here.

> I think it is possible to use the same for gf but not sure if shadowing it would be a nice idea.

Also agree. `vim-markdown` has the `ge` mapping that opens a link

**Comment by habamax** [comment]
Try again with `gf` pls.

`gf` now checks if cursor is on the link and opens it, or uses default `gf` otherwise.

**Comment by sotte** [comment]
Perfect @habamax, works like a charm. Thanks!
