### ISSUE TITLE
[Feature Request] Header Functionality Similar to Org Mode

### ISSUE THREAD

**Issue by ossie-git** [habamax/vim-asciidoctor#101]
Hi,

I'm really loving this plugin. Thanks a lot for developing it. I'm not sure if you've run into [minimd](https://github.com/shushcat/vim-minimd), a Markdown plugin, which is fantastic for Markdown documents. It basically incorporates some Org Mode capabilities to allow you to easily fold all headers (you can specify which header levels you want to see), quickly move around headers, demote and promote them (including sub-children), etc.

Is there any chance of seeing a similar feature in vim-asciidoctor? Thanks

**Comment by habamax** [comment]
* Fold is there, you have to enable it `:h g:asciidoctor_folding`
* to move around headers there are `[[` and `]]` plus I use ctags for longer jumps (together with my other vim-select plugin)

![vim-asciidoctor-1](https://user-images.githubusercontent.com/234774/127108219-e16c54dd-9764-4562-95de-578ebc93e25c.gif)


* demote and promote is smth that might be implemented in the future.

**Comment by habamax** [comment]
btw, there is "header" text-object you can also use for copy/delete/paste whole headers `ah` and `ih`:

* `vah` to select whole header
* `vih` to select contents of the header
* `dah` to delete
* etc

**Comment by ossie-git** [comment]
Thanks a lot. Can you also show all the headings at a given level? For example, in minimd, I can use `3<space>` and it would show me the document outline up to L3 (so the entire document is folded but I can see all folds up to L1, L2, and L3). This is very useful in longer documents

**Comment by habamax** [comment]
> Can you also show all the headings at a given level?

I don't know if vim can do it with its fold implementation, check `:h fold-commands`. There is also `set foldlevel=1`, 2, 3, etc to show fold with respected level.

**Comment by ossie-git** [comment]
I had a quick look and it looks like it's not supported. The minimd developer looks like he's doing something custom [https://github.com/shushcat/vim-minimd/blob/master/autoload/minimd.vim](https://github.com/shushcat/vim-minimd/blob/master/autoload/minimd.vim)

**Comment by habamax** [comment]
> The minimd developer looks like he's doing something custom

Default vim can do smth like this too, if I get it correctly:

![vim-asciidoctor-2](https://user-images.githubusercontent.com/234774/127112179-3dfc5db6-7498-4cfa-9826-5b69e542d8bc.gif)

**Comment by ossie-git** [comment]
Thanks. I tried it but for some reason, while it closes some folds, it doesn't close all of them correctly

**Comment by ossie-git** [comment]
I ran into a very old Vim plugin that kind of does this but places the result in a different buffer. It is called [folddigest](https://github.com/vim-scripts/folddigest.vim). Will see if I can find another option

**Comment by habamax** [comment]
> Thanks. I tried it but for some reason, while it closes some folds, it doesn't close all of them correctly

Looks like it works in "unexpected" way, indeed. You have to manually close all folds with `zc` first. `zM` is not enough.

**Comment by habamax** [comment]
You can try this too:

```
nnoremap <space>1 mm:%normal! zO<CR>:g/^=\{1,2}\s/normal! zc<CR>`m
nnoremap <space>2 mm:%normal! zO<CR>:g/^=\{3}\s/normal! zc<CR>`m
```

Add `set lazyredraw` if it "blinks" and maybe tune usage of the `m` mark if needed

**Comment by ossie-git** [comment]
Thanks. Tried it but it still has the same hit and miss as foldlevel

**Comment by habamax** [comment]
could you show me the screenshot?

**Comment by ossie-git** [comment]
Here's how to reproduce it. Open a document. Go to a section and open it. Go to another section and open it. Run the above mappings and it will not close all the folds. If you are standing on the fold, it will close it but not other open folds

**Comment by habamax** [comment]
![vim-asciidoctor-3](https://user-images.githubusercontent.com/234774/127120600-30327fcd-1828-4b95-a8d4-662e969ed1b6.gif)

**Comment by ossie-git** [comment]
Here's an example: https://raw.githubusercontent.com/asciidoctor/asciidoctor.org/main/docs/asciidoc-recommended-practices.adoc

Steps:

- open the document
- go to the end and open the **Literal Text** and **Tables** sections

try to use 1<space> or 2<space>. You'll notice that not both of them are closed

By the way, what application are you using for the **gifs**? I can record it if you want. Thanks a lot for your help.

**Comment by habamax** [comment]
That is screen2gif win only I think.

![vim-asciidoctor-4](https://user-images.githubusercontent.com/234774/127122729-3a620308-2bb1-4bcd-a4c6-5ece4476b740.gif)

**Comment by habamax** [comment]
Following works for me:

```
func! FoldLevel(count) abort
    if !&foldenable
        return
    endif
    try
        let pos = getcurpos()
        silent! exe "%normal! zO"
        if a:count == 1
            silent! exe 'g/^=\{1,2}\s/normal! zc'
        else
            silent! exe 'g/^=\{'..(a:count+1)..'}\s/normal! zc'
        endif
    finally
        call setpos('.', pos)
    endtry
endfunc

nnoremap <silent> <space><tab> :<C-u>call FoldLevel(v:count1)<CR>
```

* `<space><tab>`  to have `=` and `==` folded
* `2<space><tab>` to have `===` folded
* etc

**Comment by ossie-git** [comment]
Sorry about the late reply. Was just setting up gif recording. Here is what happens when I use the shortcuts. I pressed both of them in the demo

![asciidoc](https://user-images.githubusercontent.com/25382296/127128113-bafb7265-aa5f-4e6f-926f-51129203fd90.gif)

**Comment by habamax** [comment]
That is strange indeed, could you check the last updated mapping?

**Comment by habamax** [comment]
How do you open a fold and what is your foldlevelstart?

**Comment by habamax** [comment]
Maybe there is smth in your config that should be taken into account?

**Comment by habamax** [comment]
btw if you run on the same file with 2 open folds:

```
:%normal zO
:g/^=\{1,2}\s/normal! zc
```
would it have the same issue?

**Comment by ossie-git** [comment]
For your function, I noticed the following:

<space><tab> does close all folds
2<space><tab> closes all === folds but not L2 folds

foldlevelstart=-1

**Comment by ossie-git** [comment]
Mappings

![Screen Shot 2021-07-27 at 7 23 34 PM](https://user-images.githubusercontent.com/25382296/127130265-db0ae2cd-4bc7-4089-bb20-141f9da14c8d.png)

**Comment by ossie-git** [comment]
These two commands you mentioned close all folds:

```
:%normal zO
:g/^=\{1,2}\s/normal! zc
```

**Comment by habamax** [comment]
> These two commands you mentioned close all folds:
> 
> ```
> :%normal zO
> :g/^=\{1,2}\s/normal! zc
> ```

Then it is strange it doesn't work for you in a mapping.

> 2<space><tab> closes all === folds but not L2 folds

and it is implemented to do this:

```
== Fold opened 

bla bla

=== Fold closed
=== Fold closed
=== Fold closed
```

Folds are inside other folds except for the special case `=` -- it is treated as `==`, same level.

If you want to fold only parts of the header without folding nested folds then it should be implemented this way.

```
== Fold closed with contents before nested folds
=== Nested fold closed
=== Nested fold closed
```

**Comment by ossie-git** [comment]
Thanks a lot for your help. I'll try to fiddle around with it to try to get it to this. Again, I really appreciate your fantastic help :)

<img width="867" alt="Screen Shot 2021-07-27 at 4 58 34 PM" src="https://user-images.githubusercontent.com/25382296/127133534-347a93fe-7fb1-4fec-94b2-ab0bca87f358.png">

**Comment by habamax** [comment]
> If you want to fold only parts of the header without folding nested folds then it should be implemented this way.

To be clear, it is not implemented, although should be fairly easy to do. Will have a look at it later. And to doublecheck, do you need it? :)

**Comment by habamax** [comment]
> Thanks a lot for your help. I'll try to fiddle around with it to try to get it to this. Again, I really appreciate your fantastic help :)
> 
> <img alt="Screen Shot 2021-07-27 at 4 58 34 PM" width="867" src="https://user-images.githubusercontent.com/25382296/127133534-347a93fe-7fb1-4fec-94b2-ab0bca87f358.png">

In this screenshot, what would happen if you add some text after `##AWS Organizations` and/or `##IAM`?

**Comment by ossie-git** [comment]
If I add some text after either of them, it would show the text but keep the other folds closed. It would hide the text if I told it to fold to a higher level (L1 in this case)

It's be a great feature to have for longer documents. I quickly tried copying of the functions used by minimd and changing them to look for `=` instead of `#` but wasn't successful. Still learning VimL basics to try to modify some plugins and add some small scripts

**Comment by habamax** [comment]
You have to change function that is used by `foldexpr`. I will try to add another option to have folds like you expect later.

**Comment by ossie-git** [comment]
By the way, if you want a really quick demo of how [minimd](https://github.com/shushcat/vim-minimd) works, you can install it and use a Markdown file such as [this](https://raw.githubusercontent.com/emn178/markdown/master/README.md). The main functionality is in these [key-bindings](https://github.com/shushcat/vim-minimd#usage) and how neatly it does the folding and lets you move around the document. Thanks again for all your help

**Comment by habamax** [comment]
Is this what you would like to have?
![image](https://user-images.githubusercontent.com/234774/127135310-c92947fc-b0aa-4ca4-9df2-ddbeeef05fda.png)

**Comment by ossie-git** [comment]
Looks good

**Comment by habamax** [comment]
Check the latest pls

Use `let g:asciidoctor_foldnested = v:false` to activate new folding

**Comment by ossie-git** [comment]
Unfortunately, the behavior is still erratic. To minimize the likelihood of something else being at work, I created a new vimrc file and removed basically everything except for the plugin. So my **vimrc** file looks like this. The behavior is still the same as before

```vim
set nocompatible              " be iMproved, required

let g:asciidoctor_folding = 1
let g:asciidoctor_fenced_languages = ['python', 'c', 'asciidoc', 'vim', 'javascript', 'json']
let g:asciidoctor_foldnested = v:false

call plug#begin('~/.vim/plugged')

Plug 'habamax/vim-asciidoctor'

call plug#end()

filetype off
set tabstop=2
set softtabstop=2

filetype plugin indent on
set omnifunc=syntaxcomplete#Complete
syntax on
```

**Comment by habamax** [comment]
and you did update the plugin, right?

**Comment by habamax** [comment]
BTW, mappings that I have provided earlier would not work for `g:asciidoctor_foldnested = v:false`.

Now there is only 1 foldlevel that you can `zM` or `zR`.

**Comment by habamax** [comment]
You can play with the following:
```
func! FoldLevel(count) abort
    if !&foldenable
        return
    endif
    try
        let pos = getcurpos()
        silent! exe "%normal! zc"
        silent! exe 'g/^=\{'..(a:count)..'}\s/normal! zo'
    finally
        call setpos('.', pos)
    endtry
endfunc

nnoremap <silent> <space><tab> :<C-u>call FoldLevel(v:count1)<CR>
```

* it closes all folds
* and opens folds with a given prefix, `3<space><tab>` closes all folds and then open all `===` folds

**Comment by ossie-git** [comment]
Ah. I think it might be working now. If you mean that the only two options that are available are:

* close everything
* open everything
* the normal close current fold using space

then everything is working (from my limited testing). I thought that it implemented 1<space>, 2<space>, 3<space>, which isn't working

I updated the plugin (`PlugUpdate`) and verified it by reading the installed *.doc* file. I also didn't use the old mappings that you had previously shared. I am using only the above configuration file.

**Comment by habamax** [comment]
> I thought that it implemented 1<space>, 2<space>, 3<space>, which isn't working

I believe this should be user config, try `2<space><tab>` from the prev post.

**Comment by habamax** [comment]
> Ah. I think it might be working now. If you mean that the only options that are available are:
> 
> * close everything
> * open everything
> * the normal close current fold using `<space>`

Well, yes, with non-nesting folds there is only 1 level of folding you can toggle for each fold.

**Comment by ossie-git** [comment]
The new FoldLevel looks like it works but the behavior is kind of strange. When I give it a level, it opens all of the folds at that level and closes all of the ones below it. Is this what you intended? In minimd, when I give it a level, it shows me folds at that level and closes everything below it. So 2`<space>` would show me all 2L folds (folded) and nothing below. 3`<space>` would show me all 3L (folded) and nothing below that level. The behavior you implemented is a little different

**Comment by habamax** [comment]
Do you mean with the mapping I have provided? It is just an example, you should probably play with it to suit what you need.

```
func! FoldLevel(count) abort
    if !&foldenable
        return
    endif
    try
        let pos = getcurpos()

        " CHANGE HERE
        " close all folds
        silent! exe "%normal! zc"
        " searches for all =, ==, == depending on prefix 1, 2, 3
        " and executes foldopen with       normal! zo
        silent! exe 'g/^=\{'..(a:count)..'}\s/normal! zo'
        " STOP CHANGES

    finally
        call setpos('.', pos)
    endtry
endfunc

nnoremap <silent> <space><tab> :<C-u>call FoldLevel(v:count1)<CR>
```

**Comment by habamax** [comment]
> So 2`<space>` would show me all 2L folds (folded) and nothing below. 3`<space>` would show me all 3L (folded) and nothing below that level. The behavior you implemented is a little different

And this was in the original folding?! Or am I completely miss the point? Cause from your screenshot I have same behavior

**Comment by habamax** [comment]
So again, this mapping
```
func! FoldLevel(count) abort
    if !&foldenable
        return
    endif
    try
        let pos = getcurpos()
        silent! exe "%normal! zo"
        silent! exe 'g/^=\{'..a:count..'}\s/normal! zc'
    finally
        call setpos('.', pos)
    endtry
endfunc

nnoremap <silent> <space> :<C-u>call FoldLevel(v:count1)<CR>
```

`n <space>` folds all sections of level `n` leaving every other levels open


Next mapping
```
func! FoldLevel(count) abort
    if !&foldenable
        return
    endif
    try
        let pos = getcurpos()
        silent! exe 'g/^=\{'..a:count..'}\s/normal! zc'
    finally
        call setpos('.', pos)
    endtry
endfunc

nnoremap <silent> <space> :<C-u>call FoldLevel(v:count1)<CR>
```
`n <space>` folds all sections of level `n` not touching any other folds -- if they are closed, would stay closed and vice versa.

**Comment by ossie-git** [comment]
Oops. That's not the behavior the minimd gives you. It closes everything as I showed you in the original image when I ran 3`<space>`. This means can easily see my entire document and zoom in on a specific section and then open only that section or move around sections easily. So minimd will not open any levels for you unless you go to the level and press `<space>` to open it. This behavior is fantastic for working with outlines and getting various levels of visibility into your document

**Comment by ossie-git** [comment]
Here is a demo of it in action. I just use: `<space>` to close everything at the beginning and then show using 2`<space>`, 3`<space>` and moving around in the document and opening folds. I apologize for any confusion I may have caused

![minimd](https://user-images.githubusercontent.com/25382296/127155444-32270dc6-6b3a-43b2-8935-a44e4215ff5d.gif)

**Comment by habamax** [comment]
?
![vim-asciidoctor-5](https://user-images.githubusercontent.com/234774/127163875-ef5f8753-b040-4b76-aab3-86d8358d6f63.gif)

**Comment by habamax** [comment]
```
func! FoldLevel(count) abort
    if !&foldenable
        return
    endif
    if a:count == 1
        %foldclose!
    else
        let &foldlevel = a:count - 1
    endif
endfunc

nnoremap <space> :<C-u>call FoldLevel(v:count1)<CR>
```

With the latest master and this snippet it should work similar to minimd. (no toggle, `1<space>`, `2<space>`, etc)

**Comment by ossie-git** [comment]
The general folding is working very nicely :) but the `FoldLevel` isn't working as expected. When I press `2<space>`, it opens up the entire document as shown below. Thanks a lot

![asciidoc](https://user-images.githubusercontent.com/25382296/127205323-a438aad2-cebe-4bf6-85a4-6733d7af5250.gif)

**Comment by habamax** [comment]
It works with regular folding, remove foldnested

**Comment by habamax** [comment]
I mean remove

* remove this `let g:asciidoctor_foldnested = v:false`
* add this `let g:asciidoctor_foldtitle_as_h1 = 0`

**Comment by ossie-git** [comment]
Wow. Looks like it works. Thanks a million. You've been super helpful 😃   I'll test it out over the next few days and report any issues

**Comment by habamax** [comment]
@ossie-git check latest master.

```
MAPPINGS                                                *asciidoctor-mappings*

*<Plug>(AsciidoctorFold)*    Fold sections in a special way.

If
* no count is provided, toggle current fold;
* count is 1, fold all;
* count is n, open folds up to foldlevel n.
```

You can map it (as descirbed in help topic) or put it into `after/ftplugin/asciidoctor.vim`:

```
nmap <buffer> <space> <Plug>(AsciidoctorFold)
```

**Comment by ossie-git** [comment]
So far so good. Will continue testing this week

**Comment by habamax** [comment]
@ossie-git check latest with support for promote/demote sections

Example mappings are:
```
nmap <buffer> = <Plug>(AsciidoctorSectionPromote)
nmap <buffer> - <Plug>(AsciidoctorSectionDemote)
```

* doesn't work with underlined sections
* fails with "fake" sections (like `==` somewhere in `source` blocks)
