### ISSUE TITLE
Quesion: how to tell that habamax/asciidoctor replaced standard syntax (asciidoc)

### ISSUE THREAD

**Issue by bybor** [habamax/vim-asciidoctor#102]
It sometimes seems that gVim lags quite a bit when editing asciidoc files, and I'd like to think that it's because of both standard and this plugin are both enabled, so If I can turn off "standard" one, it will make things better.

But probably `vim-asciidoctor` overrides/disables a standard rutime? 

Could you tell if it's so/how to check/disable standard syntax?

Thanks!

**Comment by habamax** [comment]
Check output of the `:set ft?`. If it is `asciidoc` -- you use default built-in filetype.

vim-asciidoctor sets `asciidoctor` filetype:
![image](https://user-images.githubusercontent.com/234774/132121040-eead8dc2-57a7-4144-84fa-a0c2dab2c605.png)


Gvim might lag if you have "a big" file and folding turned on.

**Comment by bybor** [comment]
Thanks!
