### ISSUE TITLE
Add syntax highlighting for titled admonition blocks

### ISSUE THREAD

**Issue by wjsetzer** [habamax/vim-asciidoctor#12]
Problem:
Admonition block titles and deliminators (`====`) are not highlighted for titled blocks

Expected behavior:
Admonition type (e.g. `[INFO]`), title, and deliminators will all be highlighted the same color.

Explanation:
The asciidoc specs and asciidoctor examples allow titling admonition blocks. Example:

```asciidoc
[IMPORTANT]
.This is a title
====
This is the block
====
```

Currently, vim-asciidoctor does not highlight the title and deliminators in admonitions with a title.

**Comment by habamax** [comment]
yep, and if you change caption and [important] it will be highlighted.

I will have a look into it, thx.

**Comment by habamax** [comment]
I have kind of fixed it :)

I have just stopped treating admonition blocks as regions:

1. It probably is OK for admonitions -- and it solves this particular issue
2. In general it is not solved for other blocks, ie, if you insert
   caption in between of the [source] and === it would break
   highlighting.

While there is regexp that might solve the issue -- it would make syntax
highlighting slower. And with this regexp Caption will be highlighted as
not a caption but as a part of the block.
