### ISSUE TITLE
Correctly handle attribute values over multiple lines

### ISSUE THREAD

**Issue by nkalvi** [habamax/vim-asciidoctor#13]
Thank you very much for the plugin - very nicely done!

Could you improve handling of attribute values to include [soft/hard wrapped values](https://asciidoctor.org/docs/user-manual/#splitting-attribute-values-over-multiple-lines)?

Also, I'd prefer to differentiate comments from attribute assignments - is the coloring scheme customizable?

**Comment by habamax** [comment]
> Also, I'd prefer to differentiate comments from attribute assignments - is the coloring scheme customizable?

It is! Use `:hi asciidoctorOption guifg=...` or `hi link asciidoctorOption String`

**Comment by habamax** [comment]
> Could you improve handling of attribute values to include soft/hard wrapped values?

It looks like it is possible. But I think it would be better to only highlight `:option:` without the value of the option. What do you think?

**Comment by nkalvi** [comment]
Yes, I'd prefer that. 

I'll try different highlights - thank you!

**Comment by habamax** [comment]
I will change default option highlight from Comment to Define
