### ISSUE TITLE
support for :source-language: attribute

### ISSUE THREAD

**Issue by instinctive** [habamax/vim-asciidoctor#16]
![IMG_0033](https://user-images.githubusercontent.com/177694/66338081-3f692e00-e8f5-11e9-8aef-59bac883763d.jpeg)

**Comment by habamax** [comment]
Hi, thx for the issue -- never know such attribute exists.

Pls try the latest version.

Works only if this attribute is set up in first 20 rows of the file.
File has to be saved to apply new attribute value.

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/66376006-5ec88f80-e9b7-11e9-877c-8bd5e72edf29.png)

**Comment by instinctive** [comment]
Working for me - thank you!
