### ISSUE TITLE
Not working in neovim

### ISSUE THREAD

**Issue by lpvm** [habamax/vim-asciidoctor#17]
I tried this plugin in neovim, but it's not working.
Is it something about my system, or it's not ready for neovim?

**Comment by habamax** [comment]
Last time I checked it with neovim it worked for me.

So what exactly doesn't work?

**Comment by lpvm** [comment]
When trying to write some command, they're not available.
For example, in vim there's no problem in issuing :Asciidoctor2HTML.
But can't do it in neovim (version 0.4.2).

**Comment by habamax** [comment]
Ok, will check this tomorrow

**Comment by habamax** [comment]
I have tried it in neovim-qt 0.4.2

![image](https://user-images.githubusercontent.com/234774/67363297-bd743880-f575-11e9-991c-ed19e4776b4f.png)

Works for me.

![image](https://user-images.githubusercontent.com/234774/67363382-e5fc3280-f575-11e9-9fe2-44cf3d7b57a2.png)

![image](https://user-images.githubusercontent.com/234774/67363422-f7453f00-f575-11e9-8d95-1c5831c6318b.png)


Could you describe exact steps you do?

**Comment by lpvm** [comment]
I did the same thing for neovim that I did for vim and opened the same adoc file.
Both in vim and nvim the filetype is asciidoctor.

![20191023_nvim_asciidoctor](https://user-images.githubusercontent.com/7320067/67386174-5dd55780-f58c-11e9-8a37-206090513fba.png)

```
$ nvim -v
NVIM v0.4.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/builddir/neovim-0.4.2/build/config -I/builddir/neovim-0.4.2/src -I/usr/include -I/builddir/neovim-0.4.2/build/src/nvim/auto -I/builddir/neovim-0.4.2/build/include
Compiled by void-buildslave@a-hel-fi

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
```
When running `:checkhealth` from inside `nvim`:
## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for
  diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /bin/python2 does not have the "neovim" module. :help provider-python
          /bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /bin/python is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /usr/sbin/python3
  - INFO: Other python executable: /sbin/python3
  - INFO: Python version: 3.6.9
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v12.11.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

**Comment by habamax** [comment]
could you show me what is `:verbose set ft` on your adoc file?

**Comment by lpvm** [comment]
Sure:

```
  filetype=asciidoctor                                                                                               
        Last set from ~/.config/nvim/plugged/vim-asciidoctor/ftdetect/asciidoctor.vim line 1  
```

**Comment by habamax** [comment]
can you:

1. open adoc file
2. `:compiler asciidoctor2html`
3. `:make`

?

**Comment by lpvm** [comment]
I don't know exactly what to expect from those commands.
It generated the `html` file corresponding to the `adoc` one.

**Comment by habamax** [comment]
> 
> 
> I don't know exactly what to expect from those commands.
> It generated the `html` file corresponding to the `adoc` one.

Yeah it should generate html. And basically `:Asciidoctor2HTML` command calls them. 

Well, this is kind of strange.

Can you
1. open adoc file
2. `:command! -buffer Asciidoctor2HTML2 :compiler asciidoctor2html | :make`
3. `:Asciidoctor2HTML2`
?

pt.2 is the way Asciidoctor2HTML command is created in plugin

**Comment by habamax** [comment]
Another thing to check whether filetype plugin is sourced by vim or not:

1. open `~/.config/nvim/plugged/vim-asciidoctor/ftplugin/asciidoctor.vim`
2. add `echomsg "asciidoctor ftplugin..."`

```
" Vim filetype plugin
" Language:	asciidoctor
" Maintainer:	Maxim Kim <habamax@gmail.com>
" Filenames:    *.adoc

if exists("b:did_ftplugin")
	finish
endif

echoerr "asciidoctor ftplugin..."

if exists('b:undo_ftplugin')
	let b:undo_ftplugin .= "|setl cms< com< fo< flp< inex< efm<"
else
	let b:undo_ftplugin = "setl cms< com< fo< flp< inex< efm<"
endif
...
```
3. save it and restart vim
4. open adoc file `nvim file.adoc`


There should be message:
![image](https://user-images.githubusercontent.com/234774/67397340-c08d1a00-f5b1-11e9-908d-b20e7a9f1906.png)

**Comment by habamax** [comment]
Also pls check if `b:did_ftplugin` variable is not setup

1. open adoc file
2. `:echo b:did_ftplugin`

it should be like:
![image](https://user-images.githubusercontent.com/234774/67398147-e8c94880-f5b2-11e9-87f3-27c5368d2862.png)

If it is not like that, then you have to find who sets it.

**Comment by habamax** [comment]
Could you also

1. run nvim with `nvim -V20vimlog file.adoc`
2. exit nvim
3. attach vimlog file here?

**Comment by lpvm** [comment]
Regarding `b:did_ftplugin` it echoed nothing.

Please, find the `vimlog` attached, after opening and executing the steps:
```
:compiler asciidoctor2html
:make
```

[vimlog.gz](https://github.com/habamax/vim-asciidoctor/files/3763018/vimlog.gz)

**Comment by habamax** [comment]
> 
> 
> Regarding `b:did_ftplugin` it echoed nothing.

Hmm, it means it was set up, pls check `:echo exists("b:did_ftplugin")`

> Please, find the `vimlog` attached, after opening and executing the steps:
thx, will try to check it.

**Comment by habamax** [comment]
Also pls try `redir @*> | scriptnames | redir END`

It will put all loaded scripts to clipboard, pls, paste it here.

**Comment by habamax** [comment]
so indeed I can see from vimlog you have provided that b:did_ftplugin is set up

```
line 17: sourcing "/home/myuser/.config/nvim/plugged/vim-asciidoctor/ftplugin/asciidoctor.vim"
line 1: " Vim filetype plugin
line 2: " Language:^Iasciidoctor
line 3: " Maintainer:^IMaxim Kim <habamax@gmail.com>
line 4: " Filenames:    *.adoc
line 5: 
line 6: if exists("b:did_ftplugin")
line 7: ^Ifinish
finished sourcing /home/myuser/.config/nvim/plugged/vim-asciidoctor/ftplugin/asciidoctor.vim
```
it finishes sourcing of asciidoctor ftplugin file because of it.

So the question who sets it in your neovim setup?

**Comment by habamax** [comment]
there is euphoria ftplugin file loaded:

```
line 2173: sourcing "/home/myuser/.config/nvim/ftdetect/euphoria.vim"
line 1: " Vim file type file
line 2: " 
line 3: " Language:^I    Euphoria
line 4: " Language Web: http://openeuphoria.org
line 5: " Maintainer:^IJeremy Cowgar <jeremy@cowgar.com>
line 6: " Last Change:^IThu Nov 11 11:16:31 EST 2010
line 7: "
line 8: 
line 9: if exists("b:did_ftplugin")
line 10: ^Ifinish
line 11: endif
line 12: 
line 13: let b:did_ftplugin = 1
line 14: 
```

from your local configuration, which is clearly wrong as far as I understand.

files in `ftdetect/` directory should not have such logic, it should be in `ftplugin/` directory instead.

Just to dblcheck, could you remove this file `/home/myuser/.config/nvim/ftdetect/euphoria.vim` and try again?

**Comment by lpvm** [comment]
I've even removed all plugins except yours but didn't make it.

You nailed it, @habamax!  It was that `/home/myuser/.config/nvim/ftdetect/euphoria.vim`.
It was not present at the corresponding directory of `vim`.

Thank you very much for your time and effort.
All the best to you.
