### ISSUE TITLE
Syntax highlighting of code regions doesn't play well with Setex style headings

### ISSUE THREAD

**Issue by hupfdule** [habamax/vim-asciidoctor#2]
Setex style headings of level 2 are underlined with dashes. vim-asciidoctor confuses these dashes with the end of the code blocks. Therefore for this asciidoc snippet:

    Title
    =====

    Some text.

    [source,xml]
    ----
     // example code 1
    ----

    Section A
    ---------

    [source,xml]
    ----
     // example code 2
    ----

    [source,xml]
    ----
     // example code 3
    ----

    Section B
    ---------

    [source,xml]
    ----
     // example code 4
    ----

    Section C
    ---------

    [source,xml]
    ----
     // example code 5
    ----                          

Only example code 1 and 4 are highlighted correctly.

**Comment by habamax** [comment]
Well, it doesn't highlight setext for now.

It was at first but then I removed it as it was too cumbersome to make it work with all other blocks.

And it looks like it still doesn't play nice with other blocks.

**Comment by habamax** [comment]
Check this out too pls

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/54115364-572f1100-43fd-11e9-87d0-eaec1e208e70.png)

**Comment by hupfdule** [comment]
Yes, that's working fine as well!

Many thanks! 
And kudos for the fast reaction! :+1:
