### ISSUE TITLE
Syntax errors after most recent update (0112b8)

### ISSUE THREAD

**Issue by daveyarwood** [habamax/vim-asciidoctor#20]
After updating vim-asciidoctor to 0112b8bd468e656f0ad1749420743d0e9e7ffd57 this morning, I get this error whenever I open an adoc file:

![2019-11-04-101849_1061x287_scrot](https://user-images.githubusercontent.com/4909079/68132424-af66d600-feec-11e9-8ad1-157660f0ceb3.png)

**Comment by habamax** [comment]
It is definitly not the latest update as it it just the default highlight group change.

What is your vim version?

**Comment by daveyarwood** [comment]
I'm running the nightly build of Neovim, neovim-0.5.0+ubuntu1+git201911032024-93626b8-00e710e

**Comment by daveyarwood** [comment]
My linter is showing me what appears to be the problem in ftplugin/asciidoctor.vim:

![2019-11-04-103256_616x165_scrot](https://user-images.githubusercontent.com/4909079/68133504-7e87a080-feee-11e9-8b45-a35a73ef8fa2.png)

**Comment by habamax** [comment]
hmm, could you try a regular vim?

I have just recently used a default argument value for a function and I am not sure when it was introduced.

**Comment by habamax** [comment]
> 
> 
> My linter is showing me what appears to be the problem in ftplugin/asciidoctor.vim:
> 
> ![2019-11-04-103256_616x165_scrot](https://user-images.githubusercontent.com/4909079/68133504-7e87a080-feee-11e9-8b45-a35a73ef8fa2.png)

Indeed, it works in my vim and probably is not that portable :)

I will change it to `...`.

**Comment by habamax** [comment]
Could you try latest?

**Comment by daveyarwood** [comment]
That commit fixed it. :tada: Thanks for the quick fix! 

That default argument syntax is nice -- I haven't seen that before! It must have been introduced in Vim recently. Hopefully support will land soon in Neovim.

**Comment by habamax** [comment]
Looks like it is recent change in vim? Couldn't find it in release notes :) `h optional-function-argument`
```
						*optional-function-argument*
You can provide default values for positional named arguments.  This makes
them optional for function calls.  When a positional argument is not
specified at a call, the default expression is used to initialize it.
This only works for functions declared with `:function`, not for lambda
expressions |expr-lambda|.

Example: >
  function Something(key, value = 10)
     echo a:key .. ": " .. a:value
  endfunction
```
