### ISSUE TITLE
Syntax highlighting of code regions breaks, if additional options are set

### ISSUE THREAD

**Issue by hupfdule** [habamax/vim-asciidoctor#3]
The [source] header of asciidoc allow addition options, however vim-asciidoctor does not expext any.

For example:

    [source,xml,subs="verbatim,attributes"]
    ----    
    ----

is a valid asciidoc source block. But vim-asciidoctor does not highlight it, because of the `,subs="verbatim,attributes"`

**Comment by habamax** [comment]
Indeed, thx for reporting.

**Comment by habamax** [comment]
Could pls check?

**Comment by hupfdule** [comment]
Whoa, you are fast! :-)

Yes, it is working now.
