### ISSUE TITLE
Incorrect concealed single bold, italic and code

### ISSUE THREAD

**Issue by habamax** [habamax/vim-asciidoctor#33]
```
= Test

test_error_highlight
test*error*highlight
test`error`highlight

test__error__highlight
test**error**highlight
test``error``highlight
```
![image](https://user-images.githubusercontent.com/234774/69918720-bc90c980-1486-11ea-8dfa-555636e42585.png)

**Comment by habamax** [comment]
@mg979 fyi :)

**Comment by mg979** [comment]
I don't get this error, maybe it's because the cursor is on that line? the line with the cursor is always 'unconcealed'.

**Comment by mg979** [comment]
By the way, I made some new changes, maybe you are interested.

https://github.com/mg979/vim-asciidoctor/tree/syntax_changes

**Comment by habamax** [comment]
@mg979 error is that single stars in a word should not be bold: `this*should*notbebold`

**Comment by habamax** [comment]
Anyway I have fixed it, I think :).

What I dont like is the duplicity of the concealed and non concealed syntax. This should be unified in the future

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/69919341-d9300000-148c-11ea-9186-4b40249f94a8.png)

![image](https://user-images.githubusercontent.com/234774/69919345-e64cef00-148c-11ea-9166-f971d53439d5.png)

**Comment by mg979** [comment]
I see now. I integrated the changes in my branch. I think it would be better to remove the `contained` in the concealed matches, because the added groups (paragraphs and lists) probably mess up something on their own.

**Comment by mg979** [comment]
[Imgur](https://i.imgur.com/wO0hLfa.jpg)

**Comment by habamax** [comment]
> I think it would be better to remove the `contained` in the concealed matches, because the added groups (paragraphs and lists) probably mess up something on their own.

I will remove it.

**Comment by mg979** [comment]
The `asciidoctorParagraph` and `asciidoctorList` groups should go too.

The last changed broke again the lists, btw:

![Imgur](https://i.imgur.com/dj0Dla2.jpg)

**Comment by habamax** [comment]
> The `asciidoctorParagraph` and `asciidoctorList` groups should go too.

do you mean, they shouldn't be deleted?



> The last changes broke again the lists, btw:

yeah, probably try to fix it tomorrow.

**Comment by mg979** [comment]
> do you mean, they shouldn't be deleted?

Yes they should, as you already did, sorry

**Comment by habamax** [comment]
There is actually an issue even with non concealed syntax

![image](https://user-images.githubusercontent.com/234774/69919826-1d71cf00-1492-11ea-84df-e196641f9052.png)

**Comment by mg979** [comment]
test text please?

**Comment by habamax** [comment]
I have just moved definitions of list right after bold/italic and it fixed this for me :)

**Comment by habamax** [comment]
> test text please?

```
.Test bold with unordered list
* test__error__highlight
** test**error**highlight
*** test**error**highlight
*** [x] test**error**highlight
*** test``error``highlight
```

**Comment by mg979** [comment]
Yes it fixed also the issue with lists, cool

**Comment by mg979** [comment]
If you'll have time, I have some new commits there

https://github.com/mg979/vim-asciidoctor/commits/syntax_changes

not much, but there are underlines headers (#31) and some blocks (sidebar/admonition), as you can see here

![Imgur](https://i.imgur.com/wO0hLfa.jpg)

**Comment by habamax** [comment]
If you can do small PRs, it would be great.

I actually wanted both proper admonitions and setext headers.

Setext headers could not be properly highlighted as asciidoctor defines it but anyway we can try to just highlight it (incorrect :)) See my Q on stackoverflow:  https://vi.stackexchange.com/questions/22099/highlight-setext-style-asciidoctor-markdown-headers

**Comment by mg979** [comment]
Yes I noticed the same, but it doesn't matter if one knows it. Probably it is impossible.

**Comment by habamax** [comment]
> Yes I noticed the same, but it doesn't matter if one knows it

Agree
