### ISSUE TITLE
Support for highlighting plantuml syntax

### ISSUE THREAD

**Issue by hupfdule** [habamax/vim-asciidoctor#4]
https://github.com/habamax/vim-asciidoctor/blob/a02896e0b7b9cd7962e67e88177c7ef37ca63016/syntax/asciidoctor.vim#L124-L127

Apparently a plugin to highlight planuml syntax already exists:
https://github.com/aklt/plantuml-syntax

Therefore it should be quite easy to support highlighting plantuml syntax in a way similiar to source code syntax.

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/54179214-30c6af80-44a9-11e9-9ed4-05048a7142c1.png)

**Comment by habamax** [comment]
There is a new option to be introduced:

     let g:asciidoctor_highlight_plantuml = 1

off by default. Otherwise it errors if there is no plantuml installed.

**Comment by habamax** [comment]
Ohh, there is no help file I have to update with this :(

All my plugins have them and this one is not, lol.

**Comment by habamax** [comment]
Could you check it pls?

**Comment by hupfdule** [comment]
Hello,

basically it is working. But I just stumbled upon inconsistent description about how to include plantuml in an asciidoc document.

https://asciidoctor.org/docs/asciidoctor-diagram/#creating-a-diagram says:

    A diagram is written inside a literal block, which can accept several attributes. 

The examples also use **a literal block**.

https://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/#your-first-plain-text-diagram instead writes (and uses in its examples):

    Just add **a listing block** to your file using the appropriate syntax name (ditaa, graphviz or plantuml) as the block name (aka style).

https://github.com/hsanson/asciidoctor-plantuml writes:

    A diagram is written inside **an open block** inside any asciidoc file:

(The example is broken when viewed in rendered HTML, but the actual asciidoc source shows listing block as above (in constrast to an open block as written in the description).)

https://github.com/eshepelyuk/asciidoctor-plantuml.js/blob/master/README.adoc doesn't explicity mention the block style, but the first examples use a literal block:

    [plantuml#myId,mydiagram,svg,role=sequence] (1) (2) (3)
    ....
    alice -> bob
    ....

Later examples on the same page instead use a listing block:

    [plantuml]
    ----
    alice -> bob
    bob ..> alice
    ----

The [description of the built-in block styles in the official asciidoctor manual](https://asciidoctor.org/docs/user-manual/#built-in-blocks-summary) doesn't help also: 

Block | Block Name | Delimiter | Purpose | Substitutions
-- | -- | -- | -- | --
Fenced | N/A | ``` | Source code or keyboard input is displayed as entered | Verbatim
Listing | [listing] | ---- | Source code or keyboard input is displayed as entered | Verbatim
Literal | [literal] | .... | Output text is displayed exactly as entered | Verbatim
Open | Most block names | -- | Anonymous block that can act as any block except passthrough or table blocks | Varies


I think it would be best to support at least literal and listing blocks, but the specification should be made much clearer.

**Comment by hupfdule** [comment]
Another thing: It is not a real problem, but it _feels_ inconsistent, that I have to set a variable to enable plantuml syntax highlighting, but do not have to do it to enable source code highlighting.

I know, I still have to define the languages in fenced blocks that should be highlighted, but it still _feels_ a bit different.

**Comment by habamax** [comment]
> Another thing: It is not a real problem, but it _feels_ inconsistent, that I have to set a variable to enable plantuml syntax highlighting, but do not have to do it to enable source code highlighting.

I didn't know how to check if the plugin (or syntax) exists so it was lack of knowledge + don't want to ruin other's setup who doesn't have plantuml installed.

I have already changed it to be on by default (found how to do the check)

**Comment by habamax** [comment]
> I think it would be best to support at least literal and listing blocks, but the specification should be made much clearer.

Probably yes, but I couldn't make it work. It just ruins other highlighting.

```
syn region asciidoctorPlantumlBlock matchgroup=asciidoctorBlock start="^\[plantuml.\{-}\]\s*\n\.\.\.\.\+\s*$" end="^[^[]*\n\zs\.\.\.\.\+\s*$" keepend contains=@asciidoctorPlantumlHighlight
syn region asciidoctorPlantumlBlock matchgroup=asciidoctorBlock start="^\[plantuml.\{-}\]\s*\n----\+\s*$" end="^[^[]*\n\zs----+\s*$" keepend contains=@asciidoctorPlantumlHighlight

```
![image](https://user-images.githubusercontent.com/234774/54191291-aab96180-44c6-11e9-9715-59cd582c051c.png)

**Comment by habamax** [comment]
nevermind, found a type :)

**Comment by hupfdule** [comment]
> > I think it would be best to support at least literal and listing blocks, but the specification should be made much clearer.
> 
> Probably yes, but I couldn't make it work. It just ruins other highlighting.

If that's the case, I think literal blocks are enough and that should only be mentioned explicitly in the README, that other block styles are not supported to be highlighted.

**Comment by hupfdule** [comment]
> nevermind, found a typo :)

Ah, I see :-)

**Comment by habamax** [comment]
So for now plantuml is highlighted for

* listing `----`
* literal `....`
* and open `--`
