### ISSUE TITLE
'textwidth' setting is ignored

### ISSUE THREAD

**Issue by dubst3pp4** [habamax/vim-asciidoctor#44]
Hello,
I'm using the vim-asciidoctor plugin and really like it so far :-) 

But I've just discovered, that the `textwidth` setting, which I have set to `80` for asciidoctor files, is beeing ignored. When the length of a line exceeds my `textwidth` setting, the line will not get broken.

I'm not sure if vim-asciidoctor is the source of the problem, but `textwidth` works for other filetypes (Markdown, plain etc.) without problems.

Best regards,
Marc

**Comment by habamax** [comment]
That is because plugin sets `formatoptions` to `cqln`.

And `l` stands for

```
l	Long lines are not broken in insert mode: When a line was longer than
	'textwidth' when the insert command started, Vim does not
	automatically format it.
```

I don't remember why I did this though.

**Comment by habamax** [comment]
Could you try the udpate?

**Comment by dubst3pp4** [comment]
Wow, that was fast! It works now as expected! Many thanks :-)
