### ISSUE TITLE
Allow :make to invoke a Makefile

### ISSUE THREAD

**Issue by davmo** [habamax/vim-asciidoctor#52]
I have been building asciidoctor files via a `Makefile` for some time. I just installed vim-asciidoctor and find it replaces `makeprg` with settings I'd prefer to be able to avoid in order to have more control.

I may have missed how to turn off the changing of `makeprg`, but if so, then I suggest it needs to be better documented.

If such a capability doesn't exist, then I'd appreciate having one

**Comment by habamax** [comment]
> I may have missed how to turn off the changing of `makeprg`, but if so, then I suggest it needs to be better documented.

Nope, it just overrides `makeprg` with a another `compiler`.

> If such a capability doesn't exist, then I'd appreciate having one

I can have it (as with almost everything in vim) by setting compiler to whatever you want when asciidoctor buffer is loaded using autocommands. But I will remove `compiler asciidoctor2html` from ftplugin:

1. It will not be set by default, but
2. Whenever you will use one of the `Asciidoctor2HTML`, `Asciidoctor2PDF` or `Asciidoctor2DOCX`, corresponding compiler would be set (meaning current makeprg would be overwritten)
