### ISSUE TITLE
Code Block Syntax Highlighting

### ISSUE THREAD

**Issue by xxmissingnoxx** [habamax/vim-asciidoctor#59]
**What's the problem?**
Text within code blocks does not seem to have syntax highlighting:
![image](https://user-images.githubusercontent.com/17442967/75492459-d3f82980-5985-11ea-928a-a96d0b385b82.png)

The following options are set:
```vim
" Conceal *bold*, _italic_, `code` and urls in lists and paragraphs, default `0`.
" See limitations in end of the README
let g:asciidoctor_syntax_conceal = 1
let g:asciidoctor_fenced_languages = ['python', 'c', 'javascript']

" Highlight indented text, default `1`.
let g:asciidoctor_syntax_indented = 0
```
This problem seems to occur in both vim and neovim.
I'm not sure if it matters, but I am able to get correct highlighting within code blocks when I use the vim-markdown package. Are there additional settings that I'm missing or that I should check? 

**Aside**

This package seems really  handy as I generally prefer asciidoc rather than markdown. The improved speed from syntax highlighting that the package provides makes it easier to maintain larger notes in adoc format.

**Comment by habamax** [comment]
Hmm, it works for me:
![image](https://user-images.githubusercontent.com/234774/75516419-7a3b4200-5a0d-11ea-9f9e-2fe5b974a2e0.png)


1. place cursor over `def`
2. what is the output of the command `:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')` ?

**Comment by habamax** [comment]
What is also strange -- `v1` is highlighted and it shouldn't be.

Could you also check what is there?

Again, place cursor over `v1` and check what syntax is there with `:echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')`

**Comment by xxmissingnoxx** [comment]
* def returns  ['asciidoctorListingBlock']
* v1 returns []
* pygments returns []

Thank you for your ehlping out btw.

**Comment by habamax** [comment]
Ok, that looks weird ;)

0. what vim version do you use on what OS?
1. how did you install vim-asciidoctor?
2. could you paste here exact adoc file you showed on screenshot?

**Comment by habamax** [comment]
Could you

1. open vim, paste your adoc file contents to unnamed buffer
2. `:set ft=asciidoctor`

**Comment by habamax** [comment]
Can you remove all the plugins you have installed and try with only vim-asciidoctor? (or if you know how to run vim without plugins and add only vim-asciidoctor)

**Comment by habamax** [comment]
Looks like you have some plugin that do additional syntax highlighting (braces?) and it somehow interfere with asciidoctor?

**Comment by habamax** [comment]
Close it for now, feel free to reopen if you have new information/time to investigate.
