### ISSUE TITLE
trim not found when executing commands

### ISSUE THREAD

**Issue by Pepedou** [habamax/vim-asciidoctor#66]
Using a practically clean install of vim8, executed the following:

`git clone https://github.com/habamax/vim-asciidoctor.git ~/.vim/pack/my-packages/start/vim-asciidoctor`

Created a file hello.adoc and inserted:

> = Hello
> This is a new file.
> 
> == The following is a list:
> 
> 1. Element 1
> 2. Element 2
> 3. Element 3

When running any command like Asciidoctor2HTML or AsciidoctorPasteImage, got the following error:

`trim not found`

Fixed by downloading with vim-plug.

**Comment by habamax** [comment]
I am not sure when `trim` function was introduced. But given that it is simple to implement, will change it to my own.

Btw, not sure I understand, do you say that the issue with trim is fixed for you when you use vim-plug?

**Comment by Pepedou** [comment]
Yes. First I tried to install it using the "bare" method and got the error I posted.
Then I used vim-plug and it worked no problem.

**Comment by habamax** [comment]
> 
> 
> Yes. First I tried to install it using the "bare" method and got the error I posted.
> Then I used vim-plug and it worked no problem.

Hopefully now it works for you no matter if vim-plug or smth else is used!
