### ISSUE TITLE
Comment blocks aren't correctly colored

### ISSUE THREAD

**Issue by hupfdule** [habamax/vim-asciidoctor#67]
For example this document:

```asciidoc
Line 1

////
Line 2
////

Line 3
```

is rendered as:
![commenblock](https://user-images.githubusercontent.com/36069345/79762733-6af8b680-8323-11ea-9c53-c1cb4dd7664a.png)

You can see that only the start and end markers of the comment block are grey, but the _content_ of it, `Line 2` is not.

**Comment by habamax** [comment]
multilined comments are not implemented... hopefully yet.

**Comment by habamax** [comment]
For implementation reference: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#comments

**Comment by habamax** [comment]
Could you pls check?

**Comment by hupfdule** [comment]
Great! That seems to do it!

Many thanks. Also for the fast response!
