### ISSUE TITLE
How to enable folding?

### ISSUE THREAD

**Issue by doronbehar** [habamax/vim-asciidoctor#72]
Hi, your plugin looks promising but I'm having trouble getting this single feature out of it. I installed via Vim's native packages, and tried putting:

```
let g:asciidoctor_folding = 1
```

Both in `init.vim` and in a file in `plugin/settings.vim` where I usually keep external plugins specific settings.

EDIT: Also tried in my own `ftplugin/asciidoctor.vim`.

**Comment by habamax** [comment]
Could you show me the output of 

    :verbose set fdm?
    :verbose set foldexpr?
    :echo has('folding')

when open asciidoc file?

**Comment by doronbehar** [comment]
OK I think I see what's going on - if I open an adoc file I already opened in the past, [vim-stay](https://github.com/zhimsel/vim-stay) makes the folding settings of the previous session be used:

```
  foldmethod=indent
        Last set from ~/.local/share/nvim/view/=+var=+src=+git-fzf=+README.adoc= line 3
  foldexpr=0
        Last set from ~/.local/share/nvim/view/=+var=+src=+git-fzf=+README.adoc= line 4
```

However, if I open a new .adoc file with some content, the foldings do work. It's weird. For comparison, if you'll read `:help zsh`, you'd see that your can use:

```
:let g:zsh_fold_enable = 1
```

And IIRC that after I set this variable, I didn't need to do anything besides reopenning Vim and zsh's foldings where used...

**Comment by habamax** [comment]
If the user restores session where window local settings where persisted, why should ftplugin override it?

Also I am not sure there is an event in vim that is fired after session was loaded. There is `SourcePost` but it is quite general and tricky to use wrt to session files.

But in general, just reread the file `:e` after session was loaded and it will apply filetype specific settings.

**Comment by doronbehar** [comment]
> reread the file :e after session was loaded and it will apply filetype specific settings.
 
That doesn't work, but I _can_ do, for a previously opened file:

```
:setlocal ftm=expr
:setlocal foldexpr=AsciidoctorFold()
```

And then I don't have to run this again for this file.

**Comment by habamax** [comment]
> However, if I open a new .adoc file with some content, the foldings do work. It's weird. For comparison, if you'll read `:help zsh`, you'd see that your can use:

I have checked source of zsh and its folding is implemented as a syntax. It means that (most probably) whenever syntax file is read it resets foldmethod overriding what you have restored with session.

Apparently it is not the case here as I use expr foldmethod defined in ftplugin. And ftplugin is not triggered when you restore a session afaik.

**Comment by habamax** [comment]
> That doesn't work, but I _can_ do, for a previously opened file:

Hmm, that is strange, it works for me.

> ```
> :setlocal ftm=expr
> :setlocal foldexpr=AsciidoctorFold()
> ```
> 
> 
> And then I don't have to run this again for this file.

This exactly should be triggered by `:e`

```
if has("folding") && get(g:, 'asciidoctor_folding', 0)
    setlocal foldexpr=AsciidoctorFold()
    setlocal foldmethod=expr
    let b:undo_ftplugin .= " foldexpr< foldmethod<"
    let s:asciidoctor_fold_options = get(g:, 'asciidoctor_fold_options', 0)
endif
```

**Comment by doronbehar** [comment]
> I have checked source of zsh and its folding is implemented as a syntax. It means that (most probably) whenever syntax file is read it resets foldmethod overriding what you have restored with session.

Yea that sounds right to me. I was surprised you chose to pick the `expr` "domain" to define folding for a certain syntax...

**Comment by habamax** [comment]
> 
> 
> > I have checked source of zsh and its folding is implemented as a syntax. It means that (most probably) whenever syntax file is read it resets foldmethod overriding what you have restored with session.
> 
> Yea that sounds right to me. I was surprised you chose to pick the `expr` "domain" to define folding for a certain syntax...

syntax based folding for markdown-like syntaxes are really really hard to implement. I actually don't know how to do it, although I can easily can do it for c-like ones.
