### ISSUE TITLE
`gx` not working correctly to open URLs

### ISSUE THREAD

**Issue by ctonic** [habamax/vim-asciidoctor#73]
`gx` is the default command from Vim 7.4 to open URLs (see https://stackoverflow.com/questions/9458294/open-url-under-cursor-in-vim-with-browser).

I have the following line in a .adoc file opened with Vim:
````
https://www.brainlinks-braintools.uni-freiburg.de/rss-2020-workshop/[Interesting workshop from RSS 2020]
````

When doing `gx` on this line in normal mode, vim opens the clearly wrong URL `https://www.brainlinks-braintools.uni-freiburg.de/rss-2020-workshop/[Interesting/` in the browser. Removing the trailing / in the vim link doesn't help.

**Comment by habamax** [comment]
`gx` is the default command of netrw builtin plugin and there is no clear way to pass it a correct URL unless I remap `gx` providing my own implementation.

Didn't plan but will look into it.

**Comment by ctonic** [comment]
I see! Is there currently an alternative command which opens adoc links correctly?

**Comment by habamax** [comment]
> 
> 
> I see! Is there currently an alternative command which opens adoc links correctly?

I don't know. I for myself do not use netrw, so I was planning to implement it and even started some times ago:

```
"" Open URL under cursor using OS
"" http://ya.ru
"" ~/docs
"" $HOME/docs
"" C:/Users/maksim.kim/docs
"" .
func! os#open_url(word) abort
    " Windows only for now
    if !has("win32")
        return
    endif
    let word = a:word
    if word =~ '^[~.$].*'
        let word = expand(word)
    endif
    " TODO: check if barebone url
    " TODO: check if path or a filename
    " TODO: check and extract asciidoctor url
    " TODO: check and extract markdown url
    exe printf("silent !start %s", word)
    " nnoremap gx :call job_start('cmd.exe /c start '.expand("<cfile>"))<CR>
endfunc
```

But didn't have a time to do it.

**Comment by ctonic** [comment]
Thanks for the answer!

I don't know much vimscript (yet), but here is some additional information which might be useful:

Markdown plugins also have the same problem with `gx` and custom link formats.
I have [plasticboy/vim-markdown](https://github.com/plasticboy/vim-markdown) in my vimfile and it seems to be able to handle custom links correctly with ´gx´. I tried these two formats:

`<https://whatever.com>`
and
`[file:zettelkasten.md](zettelkasten.md)`

In the latter example `gx` opens the correct file no matter on which character in the string the cursor is - you can be on the first `[` or last `)` or anywhere inbetween.

**Comment by habamax** [comment]
Could you check latest master?

**Comment by ctonic** [comment]
Hi, I tested some links in my adoc files.

In my tries, links of the form `https://example.com[Text]` and `https://example.com/whatever` seemed to work correctly :)

But some problems I have found:
- There are issues if there are spaces in the link description, e.g. with `https://noteself.org/[Note Self]`: If the cursor is on or between the first `h` and the `e` in `Note`, `gx` opens the correct website. But on the rest of the string it doesn't work.
- This specific URL doesn't work: `https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU` (probably because of the `#`)
- If the `http://` part is missing it doesn't work (example: `www.google.com[test]`)
- File links don't seem to work, e.g. `file://file.adoc` and `file:file.adoc`

**Comment by habamax** [comment]
yep, it is not very robust at the moment.

* Links with spaces doesn't work as you described (and it is commented TODO in the code)
* `https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU` this one is strange, indeed. Will check
* `www` doesn't work and actually is not highlighted in asciidoctor
* `file://` -- will add it

**Comment by habamax** [comment]
* `file://` and
* `https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU`
should now work

**Comment by ctonic** [comment]
Cool :)

Here is the relevant section from the AsciiDoctor Reference: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links

For file links AsciiDoc uses two ways:
- `link:index.html[Docs]` for relative files
- `link://` for absolute links

`file://` works for  me for absolute links.

A minor problem with the previous link:
I have `(https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU)` in my adoc file. When doing `gx` on it it now opens `https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU)` (Parantese too much)
But this probably doesn't matter as one can just add a space after the link.

**Comment by habamax** [comment]
> I have `(https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU)` in my adoc file. When doing `gx` on it it now opens `https://groups.google.com/forum/#!topic/tiddlywiki/lIS6sFbrpwU)` (Parantese too much)

This I wouldn't be able to fix. (simple problem --> quite unobvious solution)

**Comment by habamax** [comment]
> * `link:index.html[Docs]` for relative files
> * `link://` for absolute links

Will have a look into this

**Comment by habamax** [comment]
> 
> 
> > * `link:index.html[Docs]` for relative files
> > * `link://` for absolute links
> 
> Will have a look into this

should now also work.

Bear in mind that `link:index.html[Docs]` would only work if your vim working directory is the same.

**Comment by habamax** [comment]
>     * There are issues if there are spaces in the link description, e.g. with `https://noteself.org/[Note Self]`: If the cursor is on or between the first `h` and the `e` in `Note`, `gx` opens the correct website. But on the rest of the string it doesn't work.

I will try to implement it this week. Although I am not sure about implementation yet, and whether I would be able to do it :)

**Comment by habamax** [comment]
Could you check latest master?

I think I have fixed "cursor is on [description separated with spaces]"

**Comment by ctonic** [comment]
Great work! :)

The fix for spaces in the link title worked well for me.
Also I think its very cool that file `link`'s are always opened in the system default application.

But I have some issues with `link:`:
- neither `link:vim.adoc` nor `link://` are recognized as links when the `[link title]` is missing
- directory paths: On my windows computer, only this path works for opening a file in a subdirectory: `link:Keybinds//2020-04-01_20-06-29_EmacsIcon.svg[Test]`. When I use `/` or `//` for the subdirectory path instead, it doesn't work. This may create issues when switching between Linux and Windows.

**Comment by habamax** [comment]
Thx for input, will check it tomorrow

**Comment by habamax** [comment]
> * neither `link:vim.adoc` nor `link://` are recognized as links when the `[link title]` is missing

This is actually not a valid asciidoctor syntax. `link` should be accompanied with `[]`

> 
> * directory paths: On my windows computer, only this path works for opening a file in a subdirectory: `link:Keybinds\\2020-04-01_20-06-29_EmacsIcon.svg[Test]`. When I use `/` or `//` for the subdirectory path instead, it doesn't work. This may create issues when switching between Linux and Windows.

forward slash:

*  works for me with full path `link:C:/Users/maksim.kim/test.txt[test file]`
* doesnt work with subdirectories (backslash doesn't work neither) `link:misc/aseprite.adoc[aseprite installation]`

Under the hood it just calls `:!start misc/aseprite.adoc` (or `!open`, `!xdg-open` for other oses) and for some reason it fails.
I have tried to change current dir with `lcd` but it has no effect.

**Comment by habamax** [comment]
Hmm, looks like I did it :)

Pls, try latest master

**Comment by ctonic** [comment]
Very cool, works perfectly :) Great work

Here are some very advanced usecases from the quick reference that probably not many use (if the goal is to implement the specification perfectly):
- This construct: `link:++https://example.org/?q=[a b]++[URL with special characters]`
- Anchor links within a file, e.g. `<<paragraphs>>`
- Anchors to other files, e.g. `<<document-b.adoc#section-b,Section B>>`

The last two are probably not very important as Vim has strong navigation features inbuilt anyways, but I just want to mention them ;)

**Comment by habamax** [comment]
> The last two are probably not very important as Vim has strong navigation features inbuilt anyways, but I just want to mention them ;)

Yep, do not plan to do anything like that. At least for now. Thx!
