### ISSUE TITLE
CrIs there documentation for folding?

### ISSUE THREAD

**Issue by whnr** [habamax/vim-asciidoctor#75]
At the moment there are only a few lines in the readme. A bit more documentation would be great. What do the settings do

```
" Fold sections, default `0`.
let g:asciidoctor_folding = 1

" Fold options, default `0`.
let g:asciidoctor_fold_options = 1
```
I assume `...folding = 1` is just enabling the folding. but what are the `fold_options`. Is there a switch for nested vs flat folding? It looks like this right now for me. Third level is folded under second level:
![grafik](https://user-images.githubusercontent.com/8114817/92419950-8af80d80-f13e-11ea-88ae-1eb5a914a159.png)

**Comment by habamax** [comment]
yes, folding is to enable folding, fold options is to fold :options:

```
= Title
Maxim Kim
v0.1, 2020-09-08 : Draft
:pdf-style: default
:doctype: article
:title-page:
:toc: left
:toclevels: 3
:sectnums:
:sectnumlevels: 4
:source-highlighter: rouge
:rouge-style: github
:!source-linenums-option:
:imagesdir: images
:chapter-label:
:icons: font
:autofit-option:
:experimental:
:compress:
```

![image](https://user-images.githubusercontent.com/234774/92438787-25456900-f1b2-11ea-813e-c255d4b2d13e.png)

**Comment by habamax** [comment]
there is no switch between "flat" and "nesting": folding is nesting with the exception of `= Title`. It is considered as the first level of headings, otherwise your whole document would be folded into a single fold.
