### ISSUE TITLE
source code blocks

### ISSUE THREAD

**Issue by frankieliu** [habamax/vim-asciidoctor#76]
Hello Maxim,

I was looking at syntax/asciidoctor.vim

around line 171,  for general source code block I was wondering if it is the only place one would need to add for regex that would match on markdown style code blocks:

example:

(three backticks)java
(three backticks)

or

(three backticks)python
(three backticks)

but looking at it I don't quite understand how you found the end of the source code block, i.e. I  don't see the match for
(four dashes)
(four dashes)

(Sorry about the parenthesis, I don't know how to escape those sequences in github)

for the start and end, so it doesn't seems as simple as adding something here in this region.  Might you guide me what I need to do to get it to work for markdown like blocks?

Thanks!

-frankie

**Comment by habamax** [comment]
Hi!
You can check `:e $VIMRUNTIME/syntax/markdown.vim` on how it is implemented for backticks.

As for asciidoctor and 4 dashes check line 173:

    syn region asciidoctorSourceBlock matchgroup=asciidoctorBlock start="^\[source\%(,.*\)*\]\s*\n\z(--\+\)\s*$" end="^.*\n\zs\z1\s*$" keepend contains=CONTAINED,asciidoctorTableCell,@asciidoctorInline,@asciidoctorUrls

It is `z1` you are looking for (`:h /\z1`), it matches the same string (dashes here) that was matched in first `\(group\)` in `start` block.
