### ISSUE TITLE
Plugin disables ALE linters

### ISSUE THREAD

**Issue by michaelrommel** [habamax/vim-asciidoctor#78]
I wanted to use this plugin together with ALE, the linting engine. Usually ALE finds linters for asciidoc files automatically, but whenever I also load this plugin, *all* default linters vanish.
Not even setting manually the linter to an executable like `alex` helped.

Has anyone else this issue? I tried to find, what goes wrong, but I only got to a point where this plugin changes the filetype from `asciidoc` to `asciidoctor`, but I could not find, how to revert that back.

Any help would be appreciated.

**Comment by habamax** [comment]
It doesn't disable ALE linting. Plugin sets up `asciidoctor` filetype&syntax which is different to builtin `asciidoc`. (I don't want it to interfere with builtin, thus a separate filetype)

I don't use ALE so can't suggest anything 100% fit to the solution, but you can try to set up `alex` linter with:

`~/.vim/after/ftplugin/asciidoctor.vim`:
```
if exists('g:loaded_ale_dont_use_this_in_other_plugins_please')
    call ale#handlers#alex#DefineLinter('asciidoctor', '--text')
endif
```

**Comment by habamax** [comment]
There is also `g:ale_linter_aliases` option you can try

```
" In ~/.vim/vimrc, or somewhere similar.
let g:ale_linter_aliases = {'asciidoctor': ['asciidoc']}
let g:ale_linters = {'asciidoctor': ['alex']}
```
