### ISSUE TITLE
Detecting the end of a link

### ISSUE THREAD

**Issue by whnr** [habamax/vim-asciidoctor#80]
I have many links in my personal asciidoc collection that are followed by some punctuation. Example: `link:https://foobar/[Barfoo],`. If there is anything but a space at the end of the closed square bracket, the title will be highlighted like an extended link.

Suggestion: Extend the highlighting logic a bit more just to highlight until the next closed square bracket, regardless of what comes next.
![grafik](https://user-images.githubusercontent.com/8114817/96917005-4f0ed280-1476-11eb-8dc9-010c5fc97ddc.png)

**Comment by habamax** [comment]
hmm
![image](https://user-images.githubusercontent.com/234774/96920119-6d47f300-14b5-11eb-978f-8669121b6253.png)

what are your asciidoctor settings?

**Comment by habamax** [comment]
Yes, you're right

![image](https://user-images.githubusercontent.com/234774/96920291-a4b69f80-14b5-11eb-8ec2-2bf471e7c469.png)

I usually use it with `let g:asciidoctor_syntax_conceal = 1` where there is no such issue

**Comment by whnr** [comment]
Yes, with `asciidoctor_syntax_conceal` it works. And I finally figured out that I have to set that _and_ `conceallevel = 2` to make pretty pages!

**Comment by habamax** [comment]
![image](https://user-images.githubusercontent.com/234774/96928413-31b32600-14c1-11eb-8c96-69c5a77a234f.png)
