### ISSUE TITLE
how to make the fenced source code(python3) highlight works?

### ISSUE THREAD

**Issue by pinggit** [habamax/vim-asciidoctor#88]
I'm been using this plugin for a while. It seems the fenced code syntax highlighting has never worked.

I've tried this:

```python3
txt = "Hello Sam!"
mytable = txt.maketrans("S", "P")
print(txt.translate(mytable))
```

and this:
```
[source, python3, linenums]
----
txt = "Hello Sam!"
mytable = txt.maketrans("S", "P")
print(txt.translate(mytable))
----
```

nothing works. can you help?

**Comment by habamax** [comment]
You have to setup `:h g:asciidoctor_fenced_languages` in your vimrc.

```
 *g:asciidoctor_fenced_languages*      Highlight syntax of source blocks
                                    Default: []
  Example: 

  let g:asciidoctor_fenced_languages = ['python', 'c', 'javascript']

  Then in your asciidoctor document:

  [source,python]
  ----
  def hello():
      print("hello world")
  ----

  should be highlighted with python syntax.
```


So to recap, 

1. put `let g:asciidoctor_fenced_languages = ['python']` to your vimrc
2.  use `[source, python]` not `[source, python3]`  -- vim doesn't know about python3 filetype

**Comment by pinggit** [comment]
I tried it, it does not work.
```
:let g:asciidoctor_fenced_languages
```
shows:
```
g:asciidoctor_fenced_languages ['python']
```
![image](https://user-images.githubusercontent.com/2038044/108388921-21942480-71dd-11eb-8d6b-e5d6981f35b2.png)

one question, how do I know currently I'm with this plugin not the others?

`:scriptnames` show these asciidoc related:
```
 18: ~/.vim/bundle/vim-asciidoctor/ftdetect/asciidoctor.vim
197: /usr/share/vim/vim81/syntax/asciidoc.vim
199: ~/.vim/bundle/vim-asciidoctor/ftplugin/asciidoctor.vim
200: ~/.vim/bundle/vim-asciidoctor/autoload/asciidoctor.vim
201: ~/.vim/bundle/vim-asciidoctor/indent/asciidoctor.vim
202: ~/.vim/bundle/vim-asciidoctor/syntax/asciidoctor.vim
207: ~/.vim/bundle/ale/ale_linters/asciidoc/alex.vim
209: ~/.vim/bundle/ale/ale_linters/asciidoc/languagetool.vim
211: ~/.vim/bundle/ale/ale_linters/asciidoc/proselint.vim
212: ~/.vim/bundle/ale/ale_linters/asciidoc/redpen.vim
213: ~/.vim/bundle/ale/ale_linters/asciidoc/textlint.vim
214: ~/.vim/bundle/ale/ale_linters/asciidoc/vale.vim
215: ~/.vim/bundle/ale/ale_linters/asciidoc/writegood.vim
```

also btw I have these prefixes in my doc, not sure if that matters

```
= my doc
:doctype: book
:toc: right
:toclevels: 3
:source-highlighter: pygments
:pygments-style: manni
:data-uri:
//:pygments-style: emacs
//:pygments-linenums-mode: inline
:pygments-linenums-mode: table
```

**Comment by habamax** [comment]
Try without linenums, like in my examples. From the phone can't check myself.

**Comment by habamax** [comment]
> one question, how do I know currently I'm with this plugin not the others?

 Check `:set ft?` when you afoc file is opened

**Comment by pinggit** [comment]
yes I actually tried exact the same thing, forgot to paste in here... no luck. wondering maybe problem of my other vim configs...

  filetype=asciidoc

**Comment by habamax** [comment]
Filetype should be asciidoctor.

чт, 18 февр. 2021 г., 19:43 pinggit <notifications@github.com>:

**Comment by habamax** [comment]
What is the output `verbose set ft?`

**Comment by pinggit** [comment]
I changed to asciidoctor, it works!
so the root cause is I was actually NOT using this plugin?

```
filetype=asciidoctor
      Last set from modeline line 1
```
so I set it from modeline.

**Comment by habamax** [comment]
Yes indeed

чт, 18 февр. 2021 г., 20:29 pinggit <notifications@github.com>:

**Comment by pinggit** [comment]
cool, I believe this is the best aciidoc vim plugin so far. Thank you for the work!

**Comment by sarna** [comment]
Hey, for me this exact setup doesn't work. `filetype` is `asciidoctor`, `:let g:asciidoctor_fenced_languages` shows `g:asciidoctor_fenced_languages ['python']`. Checked both in vim and neovim :(

**Comment by habamax** [comment]
@sarna what doesn't work exactly? I mean there are no detail what you are trying to do?

![image](https://user-images.githubusercontent.com/234774/114216113-25d3f700-996f-11eb-9653-efa5231d7f75.png)

**Comment by sarna** [comment]
@habamax Syntax highlighting doesn't work, everything's gray like in the screenshot OP posted. I followed the instructions from here - filetype is correct, added python to fenced languages.

Are there any more details/settings you want me to provide? I'll happily post the output from my system. My config is the exact same as OP's.

**Comment by habamax** [comment]
@sarna 

1. minimal adoc source
2. your asciidoctor settings

**Comment by sarna** [comment]
@habamax I actually found out what was the problem when trying to minimize my config to send it to you. It was this plugin: https://github.com/luochen1990/rainbow

When it's enabled, highlighting is broken for all code blocks.

Sorry for the trouble, thanks for your hard work on the plugin. I will first try to isolate my problems next time instead of commenting hastily :)

**Comment by habamax** [comment]
@sarna no problem :)
