### ISSUE TITLE
fenced code syntax highlight: supported languages

### ISSUE THREAD

**Issue by pinggit** [habamax/vim-asciidoctor#89]
Not sure if this is relevant to this plugin, but so far I can only make fenced code syntax highlight work for `sh` and `python`. nothing else (XML, json, etc). 
`:source-highlighter: pygments` placed at the beginning of my doc btw.
any idea?

**Comment by habamax** [comment]
Syntax highlighting in vim or in output format?

**Comment by pinggit** [comment]
I meant syntax in vim.

**Comment by habamax** [comment]
Check :h asciidoctor_fenced_languages:

```
*g:asciidoctor_fenced_languages*      Highlight syntax of source blocks
                                    Default: []
  Example: 

  let g:asciidoctor_fenced_languages = ['python', 'c', 'javascript']

  Then in your asciidoctor document:

  [source,python]
  ----
  def hello():
      print("hello world")
  ----

  should be highlighted with python syntax.
```

**Comment by habamax** [comment]
see also https://github.com/habamax/vim-asciidoctor/issues/88

**Comment by pinggit** [comment]
Thanks!
but my questions is: do we have a list of all supported languages? that `:h asciidoctor_fenced_languages:` gives three only:

* python
* c
* javascript

what about xml, shell (is it `sh`, or `bash`?), json, etc?

**Comment by habamax** [comment]
> but my questions is: do we have a list of all supported languages?

Oh, I see now.

It should support all syntaxes vim understands if you add them to that list. The help just shows what I had there at the time.

So basically, check either filetype or syntax of the file you want to add to asciidoctor_fenced_languates, i.e. open some html file and run `:set syntax?` -- it would echo `set syntax=html` -- you can add `html` to the list.

To get all the possible values, try `:e $VIMRUNTIME/syntax/` and press `<C-d>`:

![image](https://user-images.githubusercontent.com/234774/109430325-ce5a7700-7a11-11eb-83e3-bf00fe11851d.png)

**Comment by pinggit** [comment]
perfect! thanks!
