### ISSUE TITLE
[enhancement] Option to use docker-asciidoctor for the executables

### ISSUE THREAD

**Issue by CodePurble** [habamax/vim-asciidoctor#90]
A way to tell the plugin to use the [docker-asciidoctor](https://github.com/asciidoctor/docker-asciidoctor) executables will be helpful. I have tried by setting  `g:asciidoctor_executable` and friends to their equivalent Docker commands,
e.g.
```bash
let g:asciidoctor_pdf_executable = 'docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf'
```

When I run `Asciidoctor2PDF` inside NeoVim, it errors out saying that the input file is not found. The problem here is that when inside the container, `asciidoctor-pdf` expects paths relative to the container's root, therefore, in my case, the expected file path would be `/documents/<input-file>`. What it gets is the file path that is relative to the host root. A feature addition for this would be very helpful. 

I do not know VimScript, but after taking a look at the source code, perhaps a variable that allows to set what input file path to use when the plugin is in a "docker mode" (probably using another variable) will do the job.

**Comment by habamax** [comment]
Could you craft me exact command to build a pdf or/and html for exact filename?

* Filename: `~/docs/test/example.adoc`
* Command: `docker run -rm -v ......`

**Comment by CodePurble** [comment]
Outsite

> Could you craft me exact command to build a pdf or/and html for exact filename?
> 
> * Filename: `~/docs/test/example.adoc` (might be anything, this is an example)
> * Command: `docker run -rm -v ......`

If building the PDF directly from the command line, 
* Filename: `~/docs/test/example.adoc`
* Command: 
 ```bash
 docker run --rm - ~/docs/test:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf ~/docs/test/example.adoc
````

Essentially, the path to where the parent directory of the file to be built should be passed to Docker like- 

`docker ... <path-to-parent-dir>:/documents/ ... <path-to-file>`

**Comment by habamax** [comment]
Now I am confused :)

This doesn't work for you, right?
```
let g:asciidoctor_pdf_executable = 'docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf'
```
But this would work:

```
let g:asciidoctor_pdf_executable = 'docker run --rm - ~/docs/test:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf'
```

for a file `~/docs/test/example.adoc` ?

* Is `/documents/` always fixed?
* What would happen if your cwd is different to the edited file path (it is usually the case for me)? Like your cwd is `~/docs` and you try to pdf `~/docs/test/example.adoc`?

**Comment by CodePurble** [comment]
Ouch, I have made a mistake in my previous comment, sorry about that. I have corrected it there as well.

`/documents/` is fixed. I think the screenshot below will help.

![image](https://user-images.githubusercontent.com/49452779/111155334-5025d500-85ba-11eb-9167-3ad3dc09c2aa.png)

* In the first attempt, I give a path that is relative to my system's root, that is unknown in the container, and fail.
* In the second attempt, I give _just the name_ of the file at the end of the Docker command, and it works. 
* The third attempt will offer the most clarity (I hope). Here, I give a path that is relative to the **container's root**, which is also valid.

Another key point is the `~/documents/test:/documents/` part in all the commands

A reference to what the `-v` flag for Docker does (select the `-v` option) : [https://docs.docker.com/storage/volumes/#start-a-container-with-a-volume](https://docs.docker.com/storage/volumes/#start-a-container-with-a-volume)

**Comment by habamax** [comment]
Could you help me with trying:

1. open  `vim-asciidoctor/compiler/asciidoctor2pdf.vim`
2. and change `l:makeprg`

https://github.com/habamax/vim-asciidoctor/blob/568bce3b4567f7d07a68b0b2920be884ce72a068/compiler/asciidoctor2pdf.vim#L52

to

```
            \. shellescape(expand("%:t"))
```

3. use `let g:asciidoctor_pdf_executable = 'docker run --rm -v ~/docs/test:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf'`

**Comment by CodePurble** [comment]
It works! Just that I had to edit the `~/docs/test` to what I was usin.

**Comment by habamax** [comment]
Let me think about the best/simplest way to make it work for you.

For me it looks like an option to transfer `path` of the file to the `-v` parameter.

Btw, would `let g:asciidoctor_pdf_executable = 'docker run --rm asciidoctor/docker-asciidoctor asciidoctor-pdf -v ~/docs/test:/documents/'` work for you?

**Comment by CodePurble** [comment]
Not in all cases. I think leaving the choice of directory to the user would be best. In my case `$(pwd)` works best. And yes, transferring the file's path (until the parent directory) to `-v` would be the best solution.

**Comment by habamax** [comment]
> Not in all cases. Transferring the file's path (until the parent directory) to `-v` would be the sanest default, as it requires no user intervention at all.

I mean if the `-v` would be the last component of the cmd. Imagine I would just append the value of the filepath and `/documents/` to the end, would it work too?

**Comment by CodePurble** [comment]
Ohh, no no that is not possible. the `-v` component has to be before the `asciidoctor/docker-asciidoctor ...`, like it is in the previous comments.

**Comment by habamax** [comment]
And the last question (sorry for being so slow, got to do my work for money first :))

having this:
```
let g:asciidoctor_pdf_executable = 'docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf'
```

and the fix in `asciidoctor2pdf.vim`:
```
\. shellescape(expand("%:t"))
```

are you able to create pdfs?

**Comment by CodePurble** [comment]
Yes that is enough, provided that I am in the directory that the Asciidoc file to be converted is. And no worries, you can take your time!

**Comment by habamax** [comment]
Could you check latest version?

Use

```
let g:asciidoctor_use_fullpath = v:false
let g:asciidoctor_pdf_executable = 'docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf'
```

**Comment by CodePurble** [comment]
Works! Thanks for everything! :) :+1:
