### ISSUE TITLE
Long Titles break due to linebreaking, through formatting

### ISSUE THREAD

**Issue by ModProg** [habamax/vim-asciidoctor#93]
This happened when I tried to set a link as title:

```adoc
== https://sites.cs.ucsb.edu/~holl/pubs/Ragan-2009-VRPoster.pdf[Relevant Papers]
```
The workaround was adding `l` to formatoptions.

This was probably why what was the original behavior before #44

**Comment by habamax** [comment]
I can't reproduce it.

I have pasted the line to my asciidoctor buffer, deleted first `==` then typed smth before and after and nothing happened.

**Comment by habamax** [comment]
Aaand that is because I have set 

```
set formatoptions=cqjl
```

in my vimrc :)

**Comment by habamax** [comment]
I think I wouldn't be able to make happy everyone here, so I propose to use `.vim/after/ftplugin/asciidoctor.vim` to set formatoptions as needed:

```
setlocal formatoptions+=l
```

**Comment by ModProg** [comment]
Ok, I thought maybe it would be possible for the Plugin to disable that behavior only for titles and keep linebreaking for the rest of the file.

**Comment by habamax** [comment]
The option that controls this thing is not syntax element aware so I would have to implement my own linebreaking thing... which is too much for me.

PS, I for myself tend to use `gwip` once I end a paragraph of text or `gww` for a single line instead of auto linebreaks.
