### ISSUE TITLE
Concealing keeps lines "wrapped"

### ISSUE THREAD

**Issue by ModProg** [habamax/vim-asciidoctor#95]
When you have multiline code, that in concealed into one line, this happens with `vim-asciidoctor`:
![image](https://user-images.githubusercontent.com/11978847/115990371-3a48fe00-a5c3-11eb-900d-e7d14cfff388.png)

Is it possible to "unwrap" the line (but maybe keep an empty line to net shift everything needlessly around) or is that just a limitation of vims concealing that would need to be expensively worked around?

**Comment by habamax** [comment]
Could you give me some more details? The url itself and textwidth maybe?

**Comment by ModProg** [comment]
> Could you give me some more details? The url itself and textwidth maybe?

Does not make a big difference but for example, with textwidth 74:
```asciidoc
https://www.absolutely.senselessly.long.url.to.show.the.propblem.com[Just some text that pushes it over the end]
```

**Comment by habamax** [comment]
Aha, got it. It wraps around window border.

Unfortunately I don't think I can do anything about it. This should be somehow supported by vim (wrap + conceal).

**Comment by ModProg** [comment]
Seams like that issue already exists neovim/neovim/#14409
